import { getTranslations } from 'next-intl/server';
import type { MonicaCreatorCopy, MonicaGalleryCopy, MonicaStudioCopy, MonicaThemeCopy, MonicaThemesCopy } from './copy';

function rawArray<T>(value: unknown): T[] {
  return Array.isArray(value) ? value as T[] : [];
}

export async function getMonicaCreatorCopy(locale: string): Promise<MonicaCreatorCopy> {
  const t = await getTranslations({ locale, namespace: 'monica.creator' });
  return {
    badge: t('badge'),
    title: t('title'),
    description: t('description'),
    promptLabel: t('promptLabel'),
    promptPlaceholder: t('promptPlaceholder'),
    modelLabel: t('modelLabel'),
    styleLabel: t('styleLabel'),
    ratioLabel: t('ratioLabel'),
    imagesLabel: t('imagesLabel'),
    uploadReference: t('uploadReference'),
    uploadingReference: t('uploadingReference'),
    removeReference: t('removeReference'),
    generate: t('generate'),
    generating: t('generating'),
    estimatedLabel: t('estimatedLabel'),
    queueLabel: t('queueLabel'),
    resultLabel: t('resultLabel'),
    creditsUnit: t('creditsUnit'),
    ready: t('ready'),
    running: t('running'),
    notStarted: t('notStarted'),
    uploaded: t('uploaded'),
    emptyResult: t('emptyResult'),
    waitingForImages: t('waitingForImages'),
    failedNoCharge: t('failedNoCharge'),
    imageLabel: t('imageLabel'),
    initialPrompt: t('initialPrompt'),
    sessionResults: t('sessionResults'),
    openStudio: t('openStudio'),
    noReference: t('noReference'),
    modelOptions: {
      gptImage2: t('modelOptions.gptImage2'),
      nanoBanana2: t('modelOptions.nanoBanana2'),
      nanoBananaPro: t('modelOptions.nanoBananaPro'),
      seedream45: t('modelOptions.seedream45'),
    },
    assistant: {
      getIdeasToday: t('assistant.getIdeasToday'),
      getIdeasTheme: t('assistant.getIdeasTheme'),
      getIdeasFromTheme: t('assistant.getIdeasFromTheme'),
      improvePrompt: t('assistant.improvePrompt'),
      askAssistant: t('assistant.askAssistant'),
      output: t('assistant.output'),
      tryOne: t('assistant.tryOne'),
      use: t('assistant.use'),
      ideaHint: t('assistant.ideaHint'),
      ideasBasedOn: t.raw('assistant.ideasBasedOn'),
      originalPrompt: t('assistant.originalPrompt'),
      addStartingIdea: t('assistant.addStartingIdea'),
      improveNeedsPrompt: t('assistant.improveNeedsPrompt'),
      askIntro: t('assistant.askIntro'),
      askPlaceholder: t('assistant.askPlaceholder'),
      send: t('assistant.send'),
      you: t('assistant.you'),
      assistantName: t('assistant.assistantName'),
      chooseDirection: t('assistant.chooseDirection'),
      assistantDirectionHint: t('assistant.assistantDirectionHint'),
      moreIdeas: t('assistant.moreIdeas'),
      close: t('assistant.close'),
      improvedPrompt: t('assistant.improvedPrompt'),
      replacePrompt: t('assistant.replacePrompt'),
      tryAnother: t('assistant.tryAnother'),
    },
    actions: {
      submit: t('actions.submit'),
      delete: t('actions.delete'),
      favorite: t('actions.favorite'),
      download: t('actions.download'),
    },
    submitDialog: {
      title: t('submitDialog.title'),
      close: t('submitDialog.close'),
      cancel: t('submitDialog.cancel'),
      submit: t('submitDialog.submit'),
      englishTitle: t('submitDialog.englishTitle'),
      englishTitlePlaceholder: t('submitDialog.englishTitlePlaceholder'),
      theme: t('submitDialog.theme'),
      creationNote: t('submitDialog.creationNote'),
      creationNotePlaceholder: t('submitDialog.creationNotePlaceholder'),
      hint: t('submitDialog.hint'),
      loadingThemes: t('submitDialog.loadingThemes'),
      noThemes: t('submitDialog.noThemes'),
      duplicate: t('submitDialog.duplicate'),
      titleRequired: t('submitDialog.titleRequired'),
      themeRequired: t('submitDialog.themeRequired'),
    },
    styleOptions: {
      editorial: t('styleOptions.editorial'),
      cinematic: t('styleOptions.cinematic'),
      product: t('styleOptions.product'),
      illustration: t('styleOptions.illustration'),
    },
    statusLabels: {
      pending: t('statusLabels.pending'),
      queued: t('statusLabels.queued'),
      running: t('statusLabels.running'),
      succeeded: t('statusLabels.succeeded'),
      failed: t('statusLabels.failed'),
      blocked: t('statusLabels.blocked'),
      cancelled: t('statusLabels.cancelled'),
    },
  };
}

export async function getMonicaStudioCopy(locale: string): Promise<MonicaStudioCopy> {
  const t = await getTranslations({ locale, namespace: 'monica.studio' });
  return {
    title: t('title'),
    description: t('description'),
    myImages: t('myImages'),
    refresh: t('refresh'),
    loading: t('loading'),
    empty: t('empty'),
    privateStatus: t('privateStatus'),
    submit: t('submit'),
    noTheme: t('noTheme'),
    generated: t('generated'),
    prompt: t('prompt'),
    theme: t('theme'),
    model: t('model'),
    viewPrompt: t('viewPrompt'),
    close: t('close'),
    cancel: t('cancel'),
    submitImage: t('submitImage'),
    creatorNote: t('creatorNote'),
    creatorNotePlaceholder: t('creatorNotePlaceholder'),
    submitHint: t('submitHint'),
    submitDialog: {
      title: t('submitDialog.title'),
      close: t('submitDialog.close'),
      cancel: t('submitDialog.cancel'),
      submit: t('submitDialog.submit'),
      englishTitle: t('submitDialog.englishTitle'),
      englishTitlePlaceholder: t('submitDialog.englishTitlePlaceholder'),
      theme: t('submitDialog.theme'),
      creationNote: t('submitDialog.creationNote'),
      creationNotePlaceholder: t('submitDialog.creationNotePlaceholder'),
      hint: t('submitDialog.hint'),
      loadingThemes: t('submitDialog.loadingThemes'),
      noThemes: t('submitDialog.noThemes'),
      duplicate: t('submitDialog.duplicate'),
      titleRequired: t('submitDialog.titleRequired'),
      themeRequired: t('submitDialog.themeRequired'),
    },
    createTitle: t('createTitle'),
    ideaThemeLabel: t('ideaThemeLabel'),
    noIdeaTheme: t('noIdeaTheme'),
    filters: {
      searchPlaceholder: t('filters.searchPlaceholder'),
      pendingReview: t('filters.pendingReview'),
    },
    tabs: {
      all: t('tabs.all'),
      submitted: t('tabs.submitted'),
      approved: t('tabs.approved'),
      rejected: t('tabs.rejected'),
    },
    statusLabels: {
      active: t('statusLabels.active'),
      approved: t('statusLabels.approved'),
      blocked: t('statusLabels.blocked'),
      draft: t('statusLabels.draft'),
      failed: t('statusLabels.failed'),
      generated: t('statusLabels.generated'),
      pending: t('statusLabels.pending'),
      private: t('statusLabels.private'),
      published: t('statusLabels.published'),
      queued: t('statusLabels.queued'),
      rejected: t('statusLabels.rejected'),
      running: t('statusLabels.running'),
      succeeded: t('statusLabels.succeeded'),
      under_review: t('statusLabels.under_review'),
    },
  };
}

export async function getMonicaThemesCopy(locale: string): Promise<MonicaThemesCopy> {
  const t = await getTranslations({ locale, namespace: 'monica.themes' });
  return {
    title: t('title'),
    description: t('description'),
    loading: t('loading'),
    loadMore: t('loadMore'),
    retry: t('retry'),
    empty: t('empty'),
    emptyThemes: t('emptyThemes'),
    untitled: t('untitled'),
    viewTheme: t('viewTheme'),
    createFromTheme: t('createFromTheme'),
    openDetail: t('openDetail'),
    imageDetail: t('imageDetail'),
    prompt: t('prompt'),
    close: t('close'),
    usePrompt: t('usePrompt'),
    copyPrompt: t('copyPrompt'),
    copied: t('copied'),
    useAsInspiration: t('useAsInspiration'),
    actions: {
      like: t('actions.like'),
      save: t('actions.save'),
    },
    themes: rawArray(t.raw('themes')),
  };
}

export async function getMonicaGalleryCopy(locale: string): Promise<MonicaGalleryCopy> {
  const t = await getTranslations({ locale, namespace: 'monica.gallery' });
  return {
    title: t('title'),
    description: t('description'),
    loading: t('loading'),
    empty: t('empty'),
    untitled: t('untitled'),
    openDetail: t('openDetail'),
    prompt: t('prompt'),
    usePrompt: t('usePrompt'),
    copied: t('copied'),
    actions: {
      like: t('actions.like'),
      save: t('actions.save'),
    },
  };
}

export async function getMonicaThemeCopy(locale: string): Promise<MonicaThemeCopy> {
  const t = await getTranslations({ locale, namespace: 'monica.theme' });
  return {
    date: t('date'),
    eyebrow: t('eyebrow'),
    title: t('title'),
    homeTitle: t('homeTitle'),
    homeDescription: t('homeDescription'),
    homeCta: t('homeCta'),
    recentTitle: t('recentTitle'),
    stats: rawArray(t.raw('stats')),
    tags: rawArray(t.raw('tags')),
    notes: rawArray(t.raw('notes')),
    submissionHint: t('submissionHint'),
    galleryTitle: t('galleryTitle'),
    galleryTabs: {
      featured: t('galleryTabs.featured'),
      mostLiked: t('galleryTabs.mostLiked'),
      newest: t('galleryTabs.newest'),
    },
    recent: rawArray(t.raw('recent')),
    gallery: rawArray(t.raw('gallery')),
  };
}
